### Returns the given device details
GET http://localhost:666/device/read?type=AA

### Create the new device
POST http://localhost:666/device/create
Content-Type: application/json

{
  "devices": [{
        "name":"device005",
        "devType":"AC",
        "currentState":1
    }]  
}

### Share the new device
POST http://localhost:666/device/share
Content-Type: application/json

{
  "deviceId": "msvqd5smkyp",
  "userId": "q2roriifo3b"
}

### Edit the existing device details
PUT http://localhost:666/device/edit?id=a9b47f330080
Content-Type: application/json

{
    "name":"device006",
    "devType":"AA",
    "currentState":1,
}

### Update the state of the devices
PUT http://localhost:666/device/currentState
Content-Type: application/json

{
  "deviceId" : "a9b47f330080",
  "state": 0
}

### Returns the device details
DELETE http://localhost:666/device/delete?id=msvqd5smkyp
