@host = "localhost"
@port = 666
@pathPrefix = "device"


### Returns the given device details
GET http://{host}:{port}/{pathPrefix}/read?id=a9b47f330080
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2VzIjpbXSwiX2lkIjoiNWYyNDRlZmRkZThmZmUwZmU4MGFlYjNiIiwidXNlcl9pZCI6IjcuNjMwMDE5MjE1MDM1NTMxIiwiZW1haWwiOiJyYW1lc2hAbWFpbC5jb20iLCJyZWdpc3RlcmVkRGF0ZSI6IjIwMjAtMDctMzFUMTc6MDQ6MDkuNDI0WiIsIl9fdiI6MCwiaWQiOiI1ZjI0NGVmZGRlOGZmZTBmZTgwYWViM2IiLCJpYXQiOjE1OTYyNzQ3MTd9.WxMFozzuPOQBJX2SP9GDstUTEIfCPtdfyAgWgWpJHiE

### Create the new device
POST http://{host}:{port}/{pathPrefix}/create
Content-Type: application/json

{
  "devices": [{
        "device_id":"a9b47f330080",
        "name":"device001",
        "devType":"AA",
        "currentState":1,
        "lastUpdated":"1588214153"
    }]  
}

### Create the new device
POST http://{host}:{port}/{pathPrefix}/share?id=a9b47f330080
Content-Type: application/json
{
  "userId": "ramesh"
}

### Edit the existing device details
PUT http://{host}:{port}/{pathPrefix}/edit?id=a9b47f330080
Content-Type: application/json
{
    "name":"device006",
    "devType":"AA",
    "currentState":1,
    "lastUpdated":"1588214153"
}

### Update the state of the device
PUT http://{host}:{port}/{pathPrefix}/currentState?id=a9b47f330080&state=0

### Returns the device details
DELETE http://{host}:{port}/{pathPrefix}/read?id=a9b47f330080
