### Signup the user
POST http://localhost:666/signup
Content-Type: application/json

{
  "email" : "ramesh@mail.com",
  "pass": "ram@12"
}

### Login Page
GET http://localhost:666/login

### Login the user
POST http://localhost:666/login
Content-Type: application/json

{
  "email" : "ramesh@mail.com",
  "pass": "ram@12"
}